In [3]:
import pandas as pd
df1 = pd.read_csv('../../data/modified/EDA_completed.csv')
df2 = pd.read_csv('../../data/modified/user_info.csv')

In [4]:
df1['발급회원번호'] = df1.index
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Data columns (total 44 columns):
 #   Column          Dtype
---  ------          -----
 0   Unnamed: 0      int64
 1   기준년월            int64
 2   발급회원번호          int64
 3   최초한도금액          int64
 4   카드이용한도금액        int64
 5   CA한도금액          int64
 6   일시상환론한도금액       int64
 7   월상환론한도금액        int64
 8   CA이자율_할인전       float64
 9   CL이자율_할인전       float64
 10  RV일시불이자율_할인전    float64
 11  RV현금서비스이자율_할인전  float64
 12  RV신청일자          float64
 13  RV약정청구율         float64
 14  RV최소결제비율        float64
 15  자발한도감액횟수_R12M   int64
 16  자발한도감액금액_R12M   int64
 17  자발한도감액후경과월      int64
 18  강제한도감액횟수_R12M   int64
 19  강제한도감액금액_R12M   int64
 20  강제한도감액후경과월      int64
 21  한도증액횟수_R12M     int64
 22  한도증액금액_R12M     int64
 23  한도증액후경과월        int64
 24  상향가능한도금액        int64
 25  상향가능CA한도금액      int64
 26  카드론동의여부         object
 27  월상환론상향가능한도금액    int64
 28  RV전환가능여부        object
 29  일시불ONLY전환가능여부   int64
 30  카드이용한도금액_B1M    int64
 31  카드이용한도금액_B2M    int64
 32  특별한도보유여부_R3M    int64
 33  연체감액여부_R3M      int64
 34  한도심사요청건수        int64
 35  한도요청거절건수        int64
 36  한도심사요청후경과월      int64
 37  한도심사거절후경과월      int64
 38  시장단기연체여부_R6M    int64
 39  시장단기연체여부_R3M    int64
 40  시장연체상환여부_R6M    int64
 41  시장연체상환여부_R3M    int64
 42  rv최초시작후경과일      int64
 43  카드이용한도금액_log    float64
dtypes: float64(8), int64(34), object(2)
memory usage: 1007.1+ MB

In [5]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Data columns (total 80 columns):
 #   Column              Dtype
---  ------              -----
 0   Unnamed: 0          int64
 1   기준년월                int64
 2   발급회원번호              int64
 3   남녀구분코드              int64
 4   연령                  object
 5   VIP등급코드             object
 6   최상위카드등급코드           object
 7   회원여부_이용가능           int64
 8   회원여부_이용가능_CA        int64
 9   회원여부_이용가능_카드론       int64
 10  소지여부_신용             int64
 11  소지카드수_유효_신용         int64
 12  소지카드수_이용가능_신용       int64
 13  입회일자_신용             int64
 14  입회경과개월수_신용          int64
 15  회원여부_연체             int64
 16  이용거절여부_카드론          int64
 17  동의여부_한도증액안내         int64
 18  수신거부여부_TM           int64
 19  수신거부여부_DM           int64
 20  수신거부여부_메일           int64
 21  수신거부여부_SMS          int64
 22  가입통신회사코드            int64
 23  탈회횟수_누적             int64
 24  최종탈회후경과월            int64
 25  탈회횟수_발급6개월이내        int64
 26  탈회횟수_발급1년이내         int64
 27  거주시도명               object
 28  직장시도명               object
 29  마케팅동의여부             int64
 30  유효카드수_신용체크          int64
 31  유효카드수_신용            int64
 32  유효카드수_신용_가족         int64
 33  유효카드수_체크            int64
 34  유효카드수_체크_가족         int64
 35  이용가능카드수_신용체크        int64
 36  이용가능카드수_신용          int64
 37  이용가능카드수_신용_가족       int64
 38  이용가능카드수_체크          int64
 39  이용가능카드수_체크_가족       int64
 40  이용카드수_신용체크          int64
 41  이용카드수_신용            int64
 42  이용카드수_신용_가족         int64
 43  이용카드수_체크            int64
 44  이용카드수_체크_가족         int64
 45  이용금액_R3M_신용체크       int64
 46  이용금액_R3M_신용         int64
 47  이용금액_R3M_신용_가족      int64
 48  이용금액_R3M_체크         int64
 49  이용금액_R3M_체크_가족      int64
 50  _1순위카드이용금액          int64
 51  _1순위카드이용건수          int64
 52  _1순위신용체크구분          object
 53  _2순위카드이용금액          int64
 54  _2순위카드이용건수          int64
 55  _2순위신용체크구분          object
 56  최종유효년월_신용_이용가능      float64
 57  최종유효년월_신용_이용        float64
 58  최종카드발급일자            float64
 59  보유여부_해외겸용_본인        int64
 60  이용가능여부_해외겸용_본인      int64
 61  이용여부_3M_해외겸용_본인     int64
 62  보유여부_해외겸용_신용_본인     int64
 63  이용가능여부_해외겸용_신용_본인   int64
 64  이용여부_3M_해외겸용_신용_본인  int64
 65  연회비발생카드수_B0M        int64
 66  연회비할인카드수_B0M        int64
 67  기본연회비_B0M           int64
 68  제휴연회비_B0M           int64
 69  할인금액_기본연회비_B0M      int64
 70  할인금액_제휴연회비_B0M      int64
 71  청구금액_기본연회비_B0M      int64
 72  청구금액_제휴연회비_B0M      int64
 73  상품관련면제카드수_B0M       int64
 74  임직원면제카드수_B0M        int64
 75  우수회원면제카드수_B0M       int64
 76  기타면제카드수_B0M         int64
 77  카드신청건수              int64
 78  Life_Stage          object
 79  최종카드발급경과월           int64
dtypes: float64(3), int64(69), object(8)
memory usage: 1.8+ GB

In [ ]:
df2.head()

,Unnamed: 0,기준년월,발급회원번호,남녀구분코드,연령,VIP등급코드,최상위카드등급코드,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,...,할인금액_제휴연회비_B0M,청구금액_기본연회비_B0M,청구금액_제휴연회비_B0M,상품관련면제카드수_B0M,임직원면제카드수_B0M,우수회원면제카드수_B0M,기타면제카드수_B0M,카드신청건수,Life_Stage,최종카드발급경과월
0,0,201807,0,2,40대,07,_,1,1,0,...,0,0,0,0,0,0,0,0,5.자녀성장기(2),22
1,1,201807,1,1,30대,_,1,1,1,1,...,0,0,0,0,0,0,0,0,4.자녀성장기(1),18
2,2,201807,2,2,40대,_,_,1,1,1,...,0,0,0,0,0,0,0,1,4.자녀성장기(1),5
3,3,201807,3,1,40대,_,_,1,1,1,...,0,0,0,0,0,0,0,0,4.자녀성장기(1),43
4,4,201807,4,2,40대,_,_,0,0,0,...,0,0,0,0,0,0,0,0,5.자녀성장기(2),17

# df1과 df2 병합

In [61]:
# '발급회원번호' 열을 기준으로 데이터프레임 정렬
df1_sorted = df1.sort_values('발급회원번호').reset_index(drop=True)
df2_sorted = df2.sort_values('발급회원번호').reset_index(drop=True)

# '발급회원번호'를 기준으로 concat 사용하여 열 단위로 병합
df = pd.concat([df1_sorted, df2_sorted], axis=1)

In [62]:
pd.set_option('display.max_columns', None)
df.head()

,Unnamed: 0,기준년월,발급회원번호,최초한도금액,카드이용한도금액,CA한도금액,일시상환론한도금액,월상환론한도금액,CA이자율_할인전,CL이자율_할인전,RV일시불이자율_할인전,RV현금서비스이자율_할인전,RV신청일자,RV약정청구율,RV최소결제비율,자발한도감액횟수_R12M,자발한도감액금액_R12M,자발한도감액후경과월,강제한도감액횟수_R12M,강제한도감액금액_R12M,강제한도감액후경과월,한도증액횟수_R12M,한도증액금액_R12M,한도증액후경과월,상향가능한도금액,상향가능CA한도금액,카드론동의여부,월상환론상향가능한도금액,RV전환가능여부,일시불ONLY전환가능여부,카드이용한도금액_B1M,카드이용한도금액_B2M,특별한도보유여부_R3M,연체감액여부_R3M,한도심사요청건수,한도요청거절건수,한도심사요청후경과월,한도심사거절후경과월,시장단기연체여부_R6M,시장단기연체여부_R3M,시장연체상환여부_R6M,시장연체상환여부_R3M,rv최초시작후경과일,카드이용한도금액_log,Unnamed: 0,기준년월,발급회원번호,남녀구분코드,연령,VIP등급코드,최상위카드등급코드,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,소지여부_신용,소지카드수_유효_신용,소지카드수_이용가능_신용,입회일자_신용,입회경과개월수_신용,회원여부_연체,이용거절여부_카드론,동의여부_한도증액안내,수신거부여부_TM,수신거부여부_DM,수신거부여부_메일,수신거부여부_SMS,가입통신회사코드,탈회횟수_누적,최종탈회후경과월,탈회횟수_발급6개월이내,탈회횟수_발급1년이내,거주시도명,직장시도명,마케팅동의여부,유효카드수_신용체크,유효카드수_신용,유효카드수_신용_가족,유효카드수_체크,유효카드수_체크_가족,이용가능카드수_신용체크,이용가능카드수_신용,이용가능카드수_신용_가족,이용가능카드수_체크,이용가능카드수_체크_가족,이용카드수_신용체크,이용카드수_신용,이용카드수_신용_가족,이용카드수_체크,이용카드수_체크_가족,이용금액_R3M_신용체크,이용금액_R3M_신용,이용금액_R3M_신용_가족,이용금액_R3M_체크,이용금액_R3M_체크_가족,_1순위카드이용금액,_1순위카드이용건수,_1순위신용체크구분,_2순위카드이용금액,_2순위카드이용건수,_2순위신용체크구분,최종유효년월_신용_이용가능,최종유효년월_신용_이용,최종카드발급일자,보유여부_해외겸용_본인,이용가능여부_해외겸용_본인,이용여부_3M_해외겸용_본인,보유여부_해외겸용_신용_본인,이용가능여부_해외겸용_신용_본인,이용여부_3M_해외겸용_신용_본인,연회비발생카드수_B0M,연회비할인카드수_B0M,기본연회비_B0M,제휴연회비_B0M,할인금액_기본연회비_B0M,할인금액_제휴연회비_B0M,청구금액_기본연회비_B0M,청구금액_제휴연회비_B0M,상품관련면제카드수_B0M,임직원면제카드수_B0M,우수회원면제카드수_B0M,기타면제카드수_B0M,카드신청건수,Life_Stage,최종카드발급경과월
0,0,201807,0,0,1935492,727075,0,0,22.995253,18.255015,17.265002,21.234294,NaN,0.0,20.0,0,0,12,0,0,12,0,0,12,0,0,Y,0,N,0,2080551,1972367,0,0,0,0,3,3,0,0,0,0,99999999,14.475873,0,201807,0,2,40대,07,_,1,1,0,1,1,1,20130101,67,0,0,1,0,0,0,0,1,1,61,0,0,경기,경기,1,2,1,0,1,0,2,1,0,1,0,1,1,0,0,0,19612,19612,0,0,0,368148,26,신용,0,0,체크,202110.0,202112.0,20160912.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5.자녀성장기(2),22
1,1,201807,1,0,999681,571881,4199692,9061169,14.793851,14.834902,10.622467,13.636621,20171009.0,100.0,10.0,0,0,12,0,0,12,0,0,12,408,137,Y,0,Z,1,1000041,999806,0,0,0,0,3,3,0,0,0,0,322,13.815193,1,201807,1,1,30대,_,1,1,1,1,1,1,1,20170801,12,0,0,0,0,0,0,0,1,1,98,0,0,서울,서울,1,1,1,0,0,0,1,1,0,0,0,1,1,0,0,0,1347574,1347574,0,0,0,1332368,46,신용,0,0,NaN,202112.0,202204.0,20170122.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4.자녀성장기(1),18
2,2,201807,2,0,8529934,2919555,4800228,15676315,14.220657,10.898218,10.250000,13.098181,NaN,0.0,10.0,0,0,12,0,0,12,0,0,12,895,281,Y,0,Z,1,7754635,7677335,0,0,0,0,3,3,0,0,0,0,99999999,15.959092,2,201807,2,2,40대,_,_,1,1,1,1,1,1,20180601,2,0,0,0,0,0,0,0,1,1,44,0,0,충남,충남,1,1,1,0,0,0,1,1,0,0,0,1,1,0,0,0,347736,347736,0,0,0,290113,5,신용,0,0,NaN,202302.0,202209.0,20180227.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,4.자녀성장기(1),5
3,3,201807,3,999660,4132759,1453506,8999881,20604475,14.838637,14.841953,10.566343,13.636244,20120130.0,100.0,10.0,0,0,12,0,0,12,0,0,12,625,195,Y,0,Z,1,3588321,3731399,0,0,0,0,3,3,0,0,0,0,2376,15.234456,3,201807,3,1,40대,_,_,1,1,1,1,2,2,20060301,149,0,0,0,1,1,0,0,1,0,0,0,0,충남,충남,1,2,2,0,0,0,2,2,0,0,0,2,2,0,0,0,35564,35564,0,0,0,11823,9,신용,107998,7,신용,201910.0,202001.0,20141231.0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,4.자녀성장기(1),43
4,4,201807,4,0,489924,903676,0,0,14.642538,14.845428,10.281752,13.276598,20120201.0,100.0,10.0,0,0,12,1,202,8,0,0,12,404,147,Y,0,N,0,484319,486013,0,0,0,0,3,3,0,0,0,0,2366,13.102008,4,201807,4,2,40대,_,_,0,0,0,1,1,0,20120501,75,0,0,0,1,1,1,1,1,0,0,0,0,부산,부산,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-2,신용,0,0,NaN,NaN,NaN,20170206.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5.자녀성장기(2),17

In [63]:
df = df.drop(df[df['최초한도금액'] == 0].index)

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 408581 entries, 3 to 2999996
Columns: 124 entries, Unnamed: 0 to 최종카드발급경과월
dtypes: float64(11), int64(103), object(10)
memory usage: 389.7+ MB

In [65]:
df = df.drop(columns=['Unnamed: 0'])

## 연령 컬럼 숫자형 데이터로 변환

In [66]:
# df['연령'] = df['연령'].str.replace(r'\D','', regex=True).astype(int)
df.head()

,기준년월,발급회원번호,최초한도금액,카드이용한도금액,CA한도금액,일시상환론한도금액,월상환론한도금액,CA이자율_할인전,CL이자율_할인전,RV일시불이자율_할인전,RV현금서비스이자율_할인전,RV신청일자,RV약정청구율,RV최소결제비율,자발한도감액횟수_R12M,자발한도감액금액_R12M,자발한도감액후경과월,강제한도감액횟수_R12M,강제한도감액금액_R12M,강제한도감액후경과월,한도증액횟수_R12M,한도증액금액_R12M,한도증액후경과월,상향가능한도금액,상향가능CA한도금액,카드론동의여부,월상환론상향가능한도금액,RV전환가능여부,일시불ONLY전환가능여부,카드이용한도금액_B1M,카드이용한도금액_B2M,특별한도보유여부_R3M,연체감액여부_R3M,한도심사요청건수,한도요청거절건수,한도심사요청후경과월,한도심사거절후경과월,시장단기연체여부_R6M,시장단기연체여부_R3M,시장연체상환여부_R6M,시장연체상환여부_R3M,rv최초시작후경과일,카드이용한도금액_log,기준년월,발급회원번호,남녀구분코드,연령,VIP등급코드,최상위카드등급코드,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,소지여부_신용,소지카드수_유효_신용,소지카드수_이용가능_신용,입회일자_신용,입회경과개월수_신용,회원여부_연체,이용거절여부_카드론,동의여부_한도증액안내,수신거부여부_TM,수신거부여부_DM,수신거부여부_메일,수신거부여부_SMS,가입통신회사코드,탈회횟수_누적,최종탈회후경과월,탈회횟수_발급6개월이내,탈회횟수_발급1년이내,거주시도명,직장시도명,마케팅동의여부,유효카드수_신용체크,유효카드수_신용,유효카드수_신용_가족,유효카드수_체크,유효카드수_체크_가족,이용가능카드수_신용체크,이용가능카드수_신용,이용가능카드수_신용_가족,이용가능카드수_체크,이용가능카드수_체크_가족,이용카드수_신용체크,이용카드수_신용,이용카드수_신용_가족,이용카드수_체크,이용카드수_체크_가족,이용금액_R3M_신용체크,이용금액_R3M_신용,이용금액_R3M_신용_가족,이용금액_R3M_체크,이용금액_R3M_체크_가족,_1순위카드이용금액,_1순위카드이용건수,_1순위신용체크구분,_2순위카드이용금액,_2순위카드이용건수,_2순위신용체크구분,최종유효년월_신용_이용가능,최종유효년월_신용_이용,최종카드발급일자,보유여부_해외겸용_본인,이용가능여부_해외겸용_본인,이용여부_3M_해외겸용_본인,보유여부_해외겸용_신용_본인,이용가능여부_해외겸용_신용_본인,이용여부_3M_해외겸용_신용_본인,연회비발생카드수_B0M,연회비할인카드수_B0M,기본연회비_B0M,제휴연회비_B0M,할인금액_기본연회비_B0M,할인금액_제휴연회비_B0M,청구금액_기본연회비_B0M,청구금액_제휴연회비_B0M,상품관련면제카드수_B0M,임직원면제카드수_B0M,우수회원면제카드수_B0M,기타면제카드수_B0M,카드신청건수,Life_Stage,최종카드발급경과월
3,201807,3,999660,4132759,1453506,8999881,20604475,14.838637,14.841953,10.566343,13.636244,20120130.0,100.0,10.0,0,0,12,0,0,12,0,0,12,625,195,Y,0,Z,1,3588321,3731399,0,0,0,0,3,3,0,0,0,0,2376,15.234456,201807,3,1,40대,_,_,1,1,1,1,2,2,20060301,149,0,0,0,1,1,0,0,1,0,0,0,0,충남,충남,1,2,2,0,0,0,2,2,0,0,0,2,2,0,0,0,35564,35564,0,0,0,11823,9,신용,107998,7,신용,201910.0,202001.0,20141231.0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,4.자녀성장기(1),43
22,201807,22,3662850,4212277,1258148,9000080,20638979,14.220314,14.877821,10.250000,13.130144,NaN,0.0,10.0,0,0,12,0,0,12,0,0,12,651,190,Y,0,Z,1,3655824,3800652,0,0,0,0,3,3,0,0,0,0,99999999,15.253514,201807,22,2,50대,_,_,1,1,1,1,1,1,19981101,237,0,0,0,1,1,1,1,0,0,0,0,0,강원,강원,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-2,신용,0,0,NaN,202201.0,NaN,20161006.0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5.자녀성장기(2),21
27,201807,27,999876,3000223,1002170,4298781,5297580,14.641165,14.820818,10.250000,13.276586,NaN,0.0,10.0,0,0,12,0,0,12,1,169,3,611,185,Y,0,Z,1,3000188,3000055,0,0,0,0,3,3,0,0,0,0,99999999,14.914198,201807,27,1,40대,_,_,1,1,1,1,2,2,20090301,113,0,0,0,0,0,0,0,1,0,0,0,0,경기,경기,1,2,2,0,0,0,2,2,0,0,0,1,1,0,0,0,669604,669604,0,0,0,960121,57,신용,0,0,신용,202301.0,202210.0,20180220.0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4.자녀성장기(1),5
34,201807,34,999961,1000370,356129,4485847,20524659,14.220000,10.898437,10.250000,13.117843,NaN,0.0,10.0,0,0,12,0,0,12,0,0,12,407,141,Y,0,Z,1,1000136,1000345,0,0,0,0,3,3,0,0,0,0,99999999,13.815881,201807,34,1,60대,_,_,1,1,1,1,1,1,20051001,154,0,0,0,1,1,1,0,1,1,45,0,0,서울,서울,1,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-2,신용,0,0,NaN,202009.0,NaN,20151001.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7.노령,33
41,201807,41,999768,5284822,1957015,0,0,16.912103,17.673692,13.547270,16.215094,NaN,0.0,20.0,0,0,12,1,197,8,0,0,12,0,0,Y,0,Z,1,6487687,6200392,0,0,0,0,3,3,0,0,0,0,99999999,15.480350,201807,41,2,40대,06,_,1,1,0,1,3,3,20080501,123,1,0,0,1,1,1,1,1,0,0,0,0,인천,인천,0,7,4,0,3,0,6,3,0,3,0,4,3,0,1,0,5764674,5580333,0,184341,0,3737304,97,신용,1031384,35,신용,202302.0,202212.0,20171116.0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,4.자녀성장기(1),8

In [67]:
df['최상위카드등급코드'] = df['최상위카드등급코드'].str.replace('_', '0').astype(int)
df.head()

,기준년월,발급회원번호,최초한도금액,카드이용한도금액,CA한도금액,일시상환론한도금액,월상환론한도금액,CA이자율_할인전,CL이자율_할인전,RV일시불이자율_할인전,RV현금서비스이자율_할인전,RV신청일자,RV약정청구율,RV최소결제비율,자발한도감액횟수_R12M,자발한도감액금액_R12M,자발한도감액후경과월,강제한도감액횟수_R12M,강제한도감액금액_R12M,강제한도감액후경과월,한도증액횟수_R12M,한도증액금액_R12M,한도증액후경과월,상향가능한도금액,상향가능CA한도금액,카드론동의여부,월상환론상향가능한도금액,RV전환가능여부,일시불ONLY전환가능여부,카드이용한도금액_B1M,카드이용한도금액_B2M,특별한도보유여부_R3M,연체감액여부_R3M,한도심사요청건수,한도요청거절건수,한도심사요청후경과월,한도심사거절후경과월,시장단기연체여부_R6M,시장단기연체여부_R3M,시장연체상환여부_R6M,시장연체상환여부_R3M,rv최초시작후경과일,카드이용한도금액_log,기준년월,발급회원번호,남녀구분코드,연령,VIP등급코드,최상위카드등급코드,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,소지여부_신용,소지카드수_유효_신용,소지카드수_이용가능_신용,입회일자_신용,입회경과개월수_신용,회원여부_연체,이용거절여부_카드론,동의여부_한도증액안내,수신거부여부_TM,수신거부여부_DM,수신거부여부_메일,수신거부여부_SMS,가입통신회사코드,탈회횟수_누적,최종탈회후경과월,탈회횟수_발급6개월이내,탈회횟수_발급1년이내,거주시도명,직장시도명,마케팅동의여부,유효카드수_신용체크,유효카드수_신용,유효카드수_신용_가족,유효카드수_체크,유효카드수_체크_가족,이용가능카드수_신용체크,이용가능카드수_신용,이용가능카드수_신용_가족,이용가능카드수_체크,이용가능카드수_체크_가족,이용카드수_신용체크,이용카드수_신용,이용카드수_신용_가족,이용카드수_체크,이용카드수_체크_가족,이용금액_R3M_신용체크,이용금액_R3M_신용,이용금액_R3M_신용_가족,이용금액_R3M_체크,이용금액_R3M_체크_가족,_1순위카드이용금액,_1순위카드이용건수,_1순위신용체크구분,_2순위카드이용금액,_2순위카드이용건수,_2순위신용체크구분,최종유효년월_신용_이용가능,최종유효년월_신용_이용,최종카드발급일자,보유여부_해외겸용_본인,이용가능여부_해외겸용_본인,이용여부_3M_해외겸용_본인,보유여부_해외겸용_신용_본인,이용가능여부_해외겸용_신용_본인,이용여부_3M_해외겸용_신용_본인,연회비발생카드수_B0M,연회비할인카드수_B0M,기본연회비_B0M,제휴연회비_B0M,할인금액_기본연회비_B0M,할인금액_제휴연회비_B0M,청구금액_기본연회비_B0M,청구금액_제휴연회비_B0M,상품관련면제카드수_B0M,임직원면제카드수_B0M,우수회원면제카드수_B0M,기타면제카드수_B0M,카드신청건수,Life_Stage,최종카드발급경과월
3,201807,3,999660,4132759,1453506,8999881,20604475,14.838637,14.841953,10.566343,13.636244,20120130.0,100.0,10.0,0,0,12,0,0,12,0,0,12,625,195,Y,0,Z,1,3588321,3731399,0,0,0,0,3,3,0,0,0,0,2376,15.234456,201807,3,1,40대,_,0,1,1,1,1,2,2,20060301,149,0,0,0,1,1,0,0,1,0,0,0,0,충남,충남,1,2,2,0,0,0,2,2,0,0,0,2,2,0,0,0,35564,35564,0,0,0,11823,9,신용,107998,7,신용,201910.0,202001.0,20141231.0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,4.자녀성장기(1),43
22,201807,22,3662850,4212277,1258148,9000080,20638979,14.220314,14.877821,10.250000,13.130144,NaN,0.0,10.0,0,0,12,0,0,12,0,0,12,651,190,Y,0,Z,1,3655824,3800652,0,0,0,0,3,3,0,0,0,0,99999999,15.253514,201807,22,2,50대,_,0,1,1,1,1,1,1,19981101,237,0,0,0,1,1,1,1,0,0,0,0,0,강원,강원,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-2,신용,0,0,NaN,202201.0,NaN,20161006.0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5.자녀성장기(2),21
27,201807,27,999876,3000223,1002170,4298781,5297580,14.641165,14.820818,10.250000,13.276586,NaN,0.0,10.0,0,0,12,0,0,12,1,169,3,611,185,Y,0,Z,1,3000188,3000055,0,0,0,0,3,3,0,0,0,0,99999999,14.914198,201807,27,1,40대,_,0,1,1,1,1,2,2,20090301,113,0,0,0,0,0,0,0,1,0,0,0,0,경기,경기,1,2,2,0,0,0,2,2,0,0,0,1,1,0,0,0,669604,669604,0,0,0,960121,57,신용,0,0,신용,202301.0,202210.0,20180220.0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4.자녀성장기(1),5
34,201807,34,999961,1000370,356129,4485847,20524659,14.220000,10.898437,10.250000,13.117843,NaN,0.0,10.0,0,0,12,0,0,12,0,0,12,407,141,Y,0,Z,1,1000136,1000345,0,0,0,0,3,3,0,0,0,0,99999999,13.815881,201807,34,1,60대,_,0,1,1,1,1,1,1,20051001,154,0,0,0,1,1,1,0,1,1,45,0,0,서울,서울,1,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-2,신용,0,0,NaN,202009.0,NaN,20151001.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7.노령,33
41,201807,41,999768,5284822,1957015,0,0,16.912103,17.673692,13.547270,16.215094,NaN,0.0,20.0,0,0,12,1,197,8,0,0,12,0,0,Y,0,Z,1,6487687,6200392,0,0,0,0,3,3,0,0,0,0,99999999,15.480350,201807,41,2,40대,06,0,1,1,0,1,3,3,20080501,123,1,0,0,1,1,1,1,1,0,0,0,0,인천,인천,0,7,4,0,3,0,6,3,0,3,0,4,3,0,1,0,5764674,5580333,0,184341,0,3737304,97,신용,1031384,35,신용,202302.0,202212.0,20171116.0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,4.자녀성장기(1),8

# 의미 파악이 어려운 컬럼 삭제

In [68]:
df = df.drop(columns=['최상위카드등급코드'])

In [69]:
# 삭제할 컬럼 리스트
columns_to_drop = ['RV신청일자','RV약정청구율','RV최소결제비율','수신거부여부_TM',
                   '수신거부여부_DM', '수신거부여부_메일', '수신거부여부_SMS',
                   '가입통신회사코드', '마케팅동의여부', '_2순위카드이용금액',
                   '_2순위카드이용건수', '_2순위신용체크구분']

# 여러 컬럼 삭제
df = df.drop(columns=columns_to_drop)

In [70]:
df = df.dropna(subset=['_1순위신용체크구분'])
df['_1순위신용체크구분'].value_counts(dropna = False)

_1순위신용체크구분
신용    396173
체크     11326
Name: count, dtype: int64

In [71]:
# '_1순위카드이용건수' 컬럼에서 0 미만인 행을 추출
negative_usage_df = df[df['_1순위카드이용건수'] < 0]

# 결과 출력
negative_usage_df.head()

,기준년월,발급회원번호,최초한도금액,카드이용한도금액,CA한도금액,일시상환론한도금액,월상환론한도금액,CA이자율_할인전,CL이자율_할인전,RV일시불이자율_할인전,RV현금서비스이자율_할인전,자발한도감액횟수_R12M,자발한도감액금액_R12M,자발한도감액후경과월,강제한도감액횟수_R12M,강제한도감액금액_R12M,강제한도감액후경과월,한도증액횟수_R12M,한도증액금액_R12M,한도증액후경과월,상향가능한도금액,상향가능CA한도금액,카드론동의여부,월상환론상향가능한도금액,RV전환가능여부,일시불ONLY전환가능여부,카드이용한도금액_B1M,카드이용한도금액_B2M,특별한도보유여부_R3M,연체감액여부_R3M,한도심사요청건수,한도요청거절건수,한도심사요청후경과월,한도심사거절후경과월,시장단기연체여부_R6M,시장단기연체여부_R3M,시장연체상환여부_R6M,시장연체상환여부_R3M,rv최초시작후경과일,카드이용한도금액_log,기준년월,발급회원번호,남녀구분코드,연령,VIP등급코드,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,소지여부_신용,소지카드수_유효_신용,소지카드수_이용가능_신용,입회일자_신용,입회경과개월수_신용,회원여부_연체,이용거절여부_카드론,동의여부_한도증액안내,탈회횟수_누적,최종탈회후경과월,탈회횟수_발급6개월이내,탈회횟수_발급1년이내,거주시도명,직장시도명,유효카드수_신용체크,유효카드수_신용,유효카드수_신용_가족,유효카드수_체크,유효카드수_체크_가족,이용가능카드수_신용체크,이용가능카드수_신용,이용가능카드수_신용_가족,이용가능카드수_체크,이용가능카드수_체크_가족,이용카드수_신용체크,이용카드수_신용,이용카드수_신용_가족,이용카드수_체크,이용카드수_체크_가족,이용금액_R3M_신용체크,이용금액_R3M_신용,이용금액_R3M_신용_가족,이용금액_R3M_체크,이용금액_R3M_체크_가족,_1순위카드이용금액,_1순위카드이용건수,_1순위신용체크구분,최종유효년월_신용_이용가능,최종유효년월_신용_이용,최종카드발급일자,보유여부_해외겸용_본인,이용가능여부_해외겸용_본인,이용여부_3M_해외겸용_본인,보유여부_해외겸용_신용_본인,이용가능여부_해외겸용_신용_본인,이용여부_3M_해외겸용_신용_본인,연회비발생카드수_B0M,연회비할인카드수_B0M,기본연회비_B0M,제휴연회비_B0M,할인금액_기본연회비_B0M,할인금액_제휴연회비_B0M,청구금액_기본연회비_B0M,청구금액_제휴연회비_B0M,상품관련면제카드수_B0M,임직원면제카드수_B0M,우수회원면제카드수_B0M,기타면제카드수_B0M,카드신청건수,Life_Stage,최종카드발급경과월
22,201807,22,3662850,4212277,1258148,9000080,20638979,14.220314,14.877821,10.25,13.130144,0,0,12,0,0,12,0,0,12,651,190,Y,0,Z,1,3655824,3800652,0,0,0,0,3,3,0,0,0,0,99999999,15.253514,201807,22,2,50대,_,1,1,1,1,1,1,19981101,237,0,0,0,0,0,0,0,강원,강원,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-2,신용,202201.0,NaN,20161006.0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5.자녀성장기(2),21
34,201807,34,999961,1000370,356129,4485847,20524659,14.220000,10.898437,10.25,13.117843,0,0,12,0,0,12,0,0,12,407,141,Y,0,Z,1,1000136,1000345,0,0,0,0,3,3,0,0,0,0,99999999,13.815881,201807,34,1,60대,_,1,1,1,1,1,1,20051001,154,0,0,0,1,45,0,0,서울,서울,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-2,신용,202009.0,NaN,20151001.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7.노령,33
45,201807,45,3428464,468846,723302,0,0,14.839988,14.849372,10.25,13.636888,0,0,12,1,200,8,0,0,12,352,123,Y,0,N,0,458957,450608,0,0,0,0,3,3,0,0,0,0,99999999,13.058032,201807,45,2,40대,_,0,0,0,1,1,0,20071001,130,0,0,0,1,100,0,1,대전,대전,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-2,신용,NaN,NaN,20151018.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4.자녀성장기(1),33
73,201807,73,3687052,420505,0,0,0,14.220000,14.881674,10.25,13.128619,0,0,12,0,0,12,0,0,12,353,114,Y,0,N,0,380860,400952,0,0,0,0,3,3,0,0,0,0,99999999,12.949214,201807,73,2,50대,_,1,0,0,1,1,0,20011201,200,0,0,0,0,0,0,0,서울,NaN,2,1,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,-2,신용,NaN,NaN,20170629.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.자녀출가기,13
136,201807,136,3790691,8712245,2793989,8999966,20623777,14.220156,14.874518,10.25,13.132904,0,0,12,0,0,12,0,0,12,0,0,Y,0,Z,1,7089863,7045686,0,0,0,0,3,3,0,0,0,0,2388,15.980240,201807,136,2,30대,_,1,1,1,1,1,1,19991001,226,0,0,0,1,45,0,1,서울,서울,2,1,0,1,0,2,1,0,1,0,1,0,0,1,0,452503,0,0,452503,0,0,-2,체크,202107.0,NaN,20160412.0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4.자녀성장기(1),27

In [72]:
df = df.loc[:, ~df.columns.duplicated()]
df.head()

,기준년월,발급회원번호,최초한도금액,카드이용한도금액,CA한도금액,일시상환론한도금액,월상환론한도금액,CA이자율_할인전,CL이자율_할인전,RV일시불이자율_할인전,RV현금서비스이자율_할인전,자발한도감액횟수_R12M,자발한도감액금액_R12M,자발한도감액후경과월,강제한도감액횟수_R12M,강제한도감액금액_R12M,강제한도감액후경과월,한도증액횟수_R12M,한도증액금액_R12M,한도증액후경과월,상향가능한도금액,상향가능CA한도금액,카드론동의여부,월상환론상향가능한도금액,RV전환가능여부,일시불ONLY전환가능여부,카드이용한도금액_B1M,카드이용한도금액_B2M,특별한도보유여부_R3M,연체감액여부_R3M,한도심사요청건수,한도요청거절건수,한도심사요청후경과월,한도심사거절후경과월,시장단기연체여부_R6M,시장단기연체여부_R3M,시장연체상환여부_R6M,시장연체상환여부_R3M,rv최초시작후경과일,카드이용한도금액_log,남녀구분코드,연령,VIP등급코드,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,소지여부_신용,소지카드수_유효_신용,소지카드수_이용가능_신용,입회일자_신용,입회경과개월수_신용,회원여부_연체,이용거절여부_카드론,동의여부_한도증액안내,탈회횟수_누적,최종탈회후경과월,탈회횟수_발급6개월이내,탈회횟수_발급1년이내,거주시도명,직장시도명,유효카드수_신용체크,유효카드수_신용,유효카드수_신용_가족,유효카드수_체크,유효카드수_체크_가족,이용가능카드수_신용체크,이용가능카드수_신용,이용가능카드수_신용_가족,이용가능카드수_체크,이용가능카드수_체크_가족,이용카드수_신용체크,이용카드수_신용,이용카드수_신용_가족,이용카드수_체크,이용카드수_체크_가족,이용금액_R3M_신용체크,이용금액_R3M_신용,이용금액_R3M_신용_가족,이용금액_R3M_체크,이용금액_R3M_체크_가족,_1순위카드이용금액,_1순위카드이용건수,_1순위신용체크구분,최종유효년월_신용_이용가능,최종유효년월_신용_이용,최종카드발급일자,보유여부_해외겸용_본인,이용가능여부_해외겸용_본인,이용여부_3M_해외겸용_본인,보유여부_해외겸용_신용_본인,이용가능여부_해외겸용_신용_본인,이용여부_3M_해외겸용_신용_본인,연회비발생카드수_B0M,연회비할인카드수_B0M,기본연회비_B0M,제휴연회비_B0M,할인금액_기본연회비_B0M,할인금액_제휴연회비_B0M,청구금액_기본연회비_B0M,청구금액_제휴연회비_B0M,상품관련면제카드수_B0M,임직원면제카드수_B0M,우수회원면제카드수_B0M,기타면제카드수_B0M,카드신청건수,Life_Stage,최종카드발급경과월
3,201807,3,999660,4132759,1453506,8999881,20604475,14.838637,14.841953,10.566343,13.636244,0,0,12,0,0,12,0,0,12,625,195,Y,0,Z,1,3588321,3731399,0,0,0,0,3,3,0,0,0,0,2376,15.234456,1,40대,_,1,1,1,1,2,2,20060301,149,0,0,0,0,0,0,0,충남,충남,2,2,0,0,0,2,2,0,0,0,2,2,0,0,0,35564,35564,0,0,0,11823,9,신용,201910.0,202001.0,20141231.0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,4.자녀성장기(1),43
22,201807,22,3662850,4212277,1258148,9000080,20638979,14.220314,14.877821,10.250000,13.130144,0,0,12,0,0,12,0,0,12,651,190,Y,0,Z,1,3655824,3800652,0,0,0,0,3,3,0,0,0,0,99999999,15.253514,2,50대,_,1,1,1,1,1,1,19981101,237,0,0,0,0,0,0,0,강원,강원,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-2,신용,202201.0,NaN,20161006.0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5.자녀성장기(2),21
27,201807,27,999876,3000223,1002170,4298781,5297580,14.641165,14.820818,10.250000,13.276586,0,0,12,0,0,12,1,169,3,611,185,Y,0,Z,1,3000188,3000055,0,0,0,0,3,3,0,0,0,0,99999999,14.914198,1,40대,_,1,1,1,1,2,2,20090301,113,0,0,0,0,0,0,0,경기,경기,2,2,0,0,0,2,2,0,0,0,1,1,0,0,0,669604,669604,0,0,0,960121,57,신용,202301.0,202210.0,20180220.0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4.자녀성장기(1),5
34,201807,34,999961,1000370,356129,4485847,20524659,14.220000,10.898437,10.250000,13.117843,0,0,12,0,0,12,0,0,12,407,141,Y,0,Z,1,1000136,1000345,0,0,0,0,3,3,0,0,0,0,99999999,13.815881,1,60대,_,1,1,1,1,1,1,20051001,154,0,0,0,1,45,0,0,서울,서울,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-2,신용,202009.0,NaN,20151001.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7.노령,33
41,201807,41,999768,5284822,1957015,0,0,16.912103,17.673692,13.547270,16.215094,0,0,12,1,197,8,0,0,12,0,0,Y,0,Z,1,6487687,6200392,0,0,0,0,3,3,0,0,0,0,99999999,15.480350,2,40대,06,1,1,0,1,3,3,20080501,123,1,0,0,0,0,0,0,인천,인천,7,4,0,3,0,6,3,0,3,0,4,3,0,1,0,5764674,5580333,0,184341,0,3737304,97,신용,202302.0,202212.0,20171116.0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,4.자녀성장기(1),8

# 날짜형 datetime형으로 변경

In [74]:
df = df.dropna(subset=['최종유효년월_신용_이용가능', '최종유효년월_신용_이용', '최종카드발급일자'])

In [76]:
df['최종유효년월_신용_이용가능'] = df['최종유효년월_신용_이용가능'].astype(int)
df['최종유효년월_신용_이용'] = df['최종유효년월_신용_이용'].astype(int)
df['최종카드발급일자'] = df['최종카드발급일자'].astype(int)

df['기준년월'] = pd.to_datetime(df['기준년월'].astype(str), format='%Y%m')
df['입회일자_신용'] = pd.to_datetime(df['입회일자_신용'].astype(str), format='%Y%m%d')
df['최종유효년월_신용_이용가능'] = pd.to_datetime(df['최종유효년월_신용_이용가능'].astype(str), format='%Y%m')
df['최종유효년월_신용_이용'] = pd.to_datetime(df['최종유효년월_신용_이용'].astype(str), format='%Y%m')
df['최종카드발급일자'] = pd.to_datetime(df['최종카드발급일자'].astype(str), format='%Y%m%d')

# 범주형 데이터를 수치형 데이터로 변환

In [78]:
categorical_columns = ['카드론동의여부', 'RV전환가능여부']

for col in categorical_columns:
    if df[col].dtype == 'object':  # 문자열 데이터에 대해서만 적용
        df[col] = df[col].apply(lambda x: 1 if x in ['Z', 'Y'] else 0)

In [81]:
df['연령'] = df['연령'].str.replace(r'\D','', regex=True).astype(int)

In [90]:
df = df.drop(columns=['VIP등급코드'])

In [94]:
df = df.drop(columns=['Life_Stage'])

In [96]:
df = df.drop(columns=['거주시도명', '직장시도명'])

In [97]:
df.head()

,기준년월,발급회원번호,최초한도금액,카드이용한도금액,CA한도금액,일시상환론한도금액,월상환론한도금액,CA이자율_할인전,CL이자율_할인전,RV일시불이자율_할인전,RV현금서비스이자율_할인전,자발한도감액횟수_R12M,자발한도감액금액_R12M,자발한도감액후경과월,강제한도감액횟수_R12M,강제한도감액금액_R12M,강제한도감액후경과월,한도증액횟수_R12M,한도증액금액_R12M,한도증액후경과월,상향가능한도금액,상향가능CA한도금액,카드론동의여부,월상환론상향가능한도금액,RV전환가능여부,일시불ONLY전환가능여부,카드이용한도금액_B1M,카드이용한도금액_B2M,특별한도보유여부_R3M,연체감액여부_R3M,한도심사요청건수,한도요청거절건수,한도심사요청후경과월,한도심사거절후경과월,시장단기연체여부_R6M,시장단기연체여부_R3M,시장연체상환여부_R6M,시장연체상환여부_R3M,rv최초시작후경과일,카드이용한도금액_log,남녀구분코드,연령,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,소지여부_신용,소지카드수_유효_신용,소지카드수_이용가능_신용,입회일자_신용,입회경과개월수_신용,회원여부_연체,이용거절여부_카드론,동의여부_한도증액안내,탈회횟수_누적,최종탈회후경과월,탈회횟수_발급6개월이내,탈회횟수_발급1년이내,유효카드수_신용체크,유효카드수_신용,유효카드수_신용_가족,유효카드수_체크,유효카드수_체크_가족,이용가능카드수_신용체크,이용가능카드수_신용,이용가능카드수_신용_가족,이용가능카드수_체크,이용가능카드수_체크_가족,이용카드수_신용체크,이용카드수_신용,이용카드수_신용_가족,이용카드수_체크,이용카드수_체크_가족,이용금액_R3M_신용체크,이용금액_R3M_신용,이용금액_R3M_신용_가족,이용금액_R3M_체크,이용금액_R3M_체크_가족,_1순위카드이용금액,_1순위카드이용건수,_1순위신용체크구분,최종유효년월_신용_이용가능,최종유효년월_신용_이용,최종카드발급일자,보유여부_해외겸용_본인,이용가능여부_해외겸용_본인,이용여부_3M_해외겸용_본인,보유여부_해외겸용_신용_본인,이용가능여부_해외겸용_신용_본인,이용여부_3M_해외겸용_신용_본인,연회비발생카드수_B0M,연회비할인카드수_B0M,기본연회비_B0M,제휴연회비_B0M,할인금액_기본연회비_B0M,할인금액_제휴연회비_B0M,청구금액_기본연회비_B0M,청구금액_제휴연회비_B0M,상품관련면제카드수_B0M,임직원면제카드수_B0M,우수회원면제카드수_B0M,기타면제카드수_B0M,카드신청건수,최종카드발급경과월
3,2018-07-01,3,999660,4132759,1453506,8999881,20604475,14.838637,14.841953,10.566343,13.636244,0,0,12,0,0,12,0,0,12,625,195,1,0,1,1,3588321,3731399,0,0,0,0,3,3,0,0,0,0,2376,15.234456,1,40,1,1,1,1,2,2,2006-03-01,149,0,0,0,0,0,0,0,2,2,0,0,0,2,2,0,0,0,2,2,0,0,0,35564,35564,0,0,0,11823,9,신용,2019-10-01,2020-01-01,2014-12-31,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,43
27,2018-07-01,27,999876,3000223,1002170,4298781,5297580,14.641165,14.820818,10.250000,13.276586,0,0,12,0,0,12,1,169,3,611,185,1,0,1,1,3000188,3000055,0,0,0,0,3,3,0,0,0,0,99999999,14.914198,1,40,1,1,1,1,2,2,2009-03-01,113,0,0,0,0,0,0,0,2,2,0,0,0,2,2,0,0,0,1,1,0,0,0,669604,669604,0,0,0,960121,57,신용,2023-01-01,2022-10-01,2018-02-20,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5
41,2018-07-01,41,999768,5284822,1957015,0,0,16.912103,17.673692,13.547270,16.215094,0,0,12,1,197,8,0,0,12,0,0,1,0,1,1,6487687,6200392,0,0,0,0,3,3,0,0,0,0,99999999,15.480350,2,40,1,1,0,1,3,3,2008-05-01,123,1,0,0,0,0,0,0,7,4,0,3,0,6,3,0,3,0,4,3,0,1,0,5764674,5580333,0,184341,0,3737304,97,신용,2023-02-01,2022-12-01,2017-11-16,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,8
61,2018-07-01,61,4330291,19242319,4959904,4569685,5617443,14.220175,10.897975,10.250000,13.132012,0,0,12,0,0,12,0,0,12,0,0,1,0,1,1,18620734,19116678,0,0,0,0,3,3,0,0,0,0,99999999,16.772623,1,70,1,1,1,1,1,1,1996-05-01,267,0,0,0,0,0,0,0,2,2,0,0,0,2,2,0,0,0,2,2,0,0,0,2958958,2958958,0,0,0,1453827,7,신용,2020-03-01,2020-04-01,2014-12-03,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,43
62,2018-07-01,62,999757,999888,185271,4801019,18218004,14.645212,11.896486,10.326660,13.341980,0,0,12,0,0,12,0,0,12,285,84,1,0,1,1,999905,999945,0,0,0,0,3,3,0,0,0,0,99999999,13.815400,2,60,1,1,1,1,1,1,2007-11-01,129,0,0,0,0,0,0,0,1,1,0,0,0,1,1,0,0,0,1,1,0,0,0,398238,398238,0,0,0,399345,77,신용,2021-09-01,2021-08-01,2016-07-30,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,24

# 라벨링

In [105]:
label_mapping = {
    '신용':1, '체크':0
}

df['_1순위신용체크구분'] = df['_1순위신용체크구분'].map(label_mapping)

In [106]:
df.head()

,기준년월,발급회원번호,최초한도금액,카드이용한도금액,CA한도금액,일시상환론한도금액,월상환론한도금액,CA이자율_할인전,CL이자율_할인전,RV일시불이자율_할인전,RV현금서비스이자율_할인전,자발한도감액횟수_R12M,자발한도감액금액_R12M,자발한도감액후경과월,강제한도감액횟수_R12M,강제한도감액금액_R12M,강제한도감액후경과월,한도증액횟수_R12M,한도증액금액_R12M,한도증액후경과월,상향가능한도금액,상향가능CA한도금액,카드론동의여부,월상환론상향가능한도금액,RV전환가능여부,일시불ONLY전환가능여부,카드이용한도금액_B1M,카드이용한도금액_B2M,특별한도보유여부_R3M,연체감액여부_R3M,한도심사요청건수,한도요청거절건수,한도심사요청후경과월,한도심사거절후경과월,시장단기연체여부_R6M,시장단기연체여부_R3M,시장연체상환여부_R6M,시장연체상환여부_R3M,rv최초시작후경과일,카드이용한도금액_log,남녀구분코드,연령,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,소지여부_신용,소지카드수_유효_신용,소지카드수_이용가능_신용,입회일자_신용,입회경과개월수_신용,회원여부_연체,이용거절여부_카드론,동의여부_한도증액안내,탈회횟수_누적,최종탈회후경과월,탈회횟수_발급6개월이내,탈회횟수_발급1년이내,유효카드수_신용체크,유효카드수_신용,유효카드수_신용_가족,유효카드수_체크,유효카드수_체크_가족,이용가능카드수_신용체크,이용가능카드수_신용,이용가능카드수_신용_가족,이용가능카드수_체크,이용가능카드수_체크_가족,이용카드수_신용체크,이용카드수_신용,이용카드수_신용_가족,이용카드수_체크,이용카드수_체크_가족,이용금액_R3M_신용체크,이용금액_R3M_신용,이용금액_R3M_신용_가족,이용금액_R3M_체크,이용금액_R3M_체크_가족,_1순위카드이용금액,_1순위카드이용건수,_1순위신용체크구분,최종유효년월_신용_이용가능,최종유효년월_신용_이용,최종카드발급일자,보유여부_해외겸용_본인,이용가능여부_해외겸용_본인,이용여부_3M_해외겸용_본인,보유여부_해외겸용_신용_본인,이용가능여부_해외겸용_신용_본인,이용여부_3M_해외겸용_신용_본인,연회비발생카드수_B0M,연회비할인카드수_B0M,기본연회비_B0M,제휴연회비_B0M,할인금액_기본연회비_B0M,할인금액_제휴연회비_B0M,청구금액_기본연회비_B0M,청구금액_제휴연회비_B0M,상품관련면제카드수_B0M,임직원면제카드수_B0M,우수회원면제카드수_B0M,기타면제카드수_B0M,카드신청건수,최종카드발급경과월
3,2018-07-01,3,999660,4132759,1453506,8999881,20604475,14.838637,14.841953,10.566343,13.636244,0,0,12,0,0,12,0,0,12,625,195,1,0,1,1,3588321,3731399,0,0,0,0,3,3,0,0,0,0,2376,15.234456,1,40,1,1,1,1,2,2,2006-03-01,149,0,0,0,0,0,0,0,2,2,0,0,0,2,2,0,0,0,2,2,0,0,0,35564,35564,0,0,0,11823,9,1,2019-10-01,2020-01-01,2014-12-31,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,43
27,2018-07-01,27,999876,3000223,1002170,4298781,5297580,14.641165,14.820818,10.250000,13.276586,0,0,12,0,0,12,1,169,3,611,185,1,0,1,1,3000188,3000055,0,0,0,0,3,3,0,0,0,0,99999999,14.914198,1,40,1,1,1,1,2,2,2009-03-01,113,0,0,0,0,0,0,0,2,2,0,0,0,2,2,0,0,0,1,1,0,0,0,669604,669604,0,0,0,960121,57,1,2023-01-01,2022-10-01,2018-02-20,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5
41,2018-07-01,41,999768,5284822,1957015,0,0,16.912103,17.673692,13.547270,16.215094,0,0,12,1,197,8,0,0,12,0,0,1,0,1,1,6487687,6200392,0,0,0,0,3,3,0,0,0,0,99999999,15.480350,2,40,1,1,0,1,3,3,2008-05-01,123,1,0,0,0,0,0,0,7,4,0,3,0,6,3,0,3,0,4,3,0,1,0,5764674,5580333,0,184341,0,3737304,97,1,2023-02-01,2022-12-01,2017-11-16,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,8
61,2018-07-01,61,4330291,19242319,4959904,4569685,5617443,14.220175,10.897975,10.250000,13.132012,0,0,12,0,0,12,0,0,12,0,0,1,0,1,1,18620734,19116678,0,0,0,0,3,3,0,0,0,0,99999999,16.772623,1,70,1,1,1,1,1,1,1996-05-01,267,0,0,0,0,0,0,0,2,2,0,0,0,2,2,0,0,0,2,2,0,0,0,2958958,2958958,0,0,0,1453827,7,1,2020-03-01,2020-04-01,2014-12-03,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,43
62,2018-07-01,62,999757,999888,185271,4801019,18218004,14.645212,11.896486,10.326660,13.341980,0,0,12,0,0,12,0,0,12,285,84,1,0,1,1,999905,999945,0,0,0,0,3,3,0,0,0,0,99999999,13.815400,2,60,1,1,1,1,1,1,2007-11-01,129,0,0,0,0,0,0,0,1,1,0,0,0,1,1,0,0,0,1,1,0,0,0,398238,398238,0,0,0,399345,77,1,2021-09-01,2021-08-01,2016-07-30,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,24

In [107]:
df.to_csv("UserInfo_Preprocessing.csv")